/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualanTempe;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import penjualanTempe.koneksi;
import java.util.Locale;
import java.util.StringTokenizer;
import java.text.NumberFormat;
import java.util.HashMap;
import java.sql.Connection;
 
import java.sql.DriverManager;
 
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
 
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.design.JasperDesign;
 
/**
 *
 * @author Majey
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private Connection dbConnection;
    private koneksi db = new koneksi();
    Statement st;
    ResultSet rs;
    public mainFrame() {
        initComponents();
        setLocationRelativeTo(this);
        labelID.setVisible(false);
        labelBeli.setVisible(false);
        labelKonsumen.setVisible(false);
        labelsupplier.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        dashPanel = new javax.swing.JPanel();
        tombolKonsumen = new javax.swing.JLabel();
        productPanel = new javax.swing.JPanel();
        tombolPenjualan = new javax.swing.JLabel();
        customersPanel = new javax.swing.JPanel();
        tombolSupplier = new javax.swing.JLabel();
        salePanel = new javax.swing.JPanel();
        tombolPembelian = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        dashboardPanel = new javax.swing.JPanel();
        greeting = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        panelSupplier = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jmlSupplier = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        resfreshData = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        labelsupplier = new javax.swing.JLabel();
        panelPembelian = new javax.swing.JPanel();
        hasilJumlah = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPembelian = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        hslHarga = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        labelBeli = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        panelKonsumen = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        hsl = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        labelKonsumen = new javax.swing.JLabel();
        panelPenjualan = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        hslJml = new javax.swing.JLabel();
        hslByr = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPenjualan = new javax.swing.JTable();
        btnCetak = new javax.swing.JButton();
        labelID = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(12, 75, 96));

        jPanel5.setBackground(new java.awt.Color(12, 75, 96));
        jPanel5.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        dashPanel.setBackground(new java.awt.Color(0, 128, 145));
        dashPanel.setPreferredSize(new java.awt.Dimension(300, 40));

        tombolKonsumen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tombolKonsumen.setForeground(new java.awt.Color(255, 255, 255));
        tombolKonsumen.setText("DATA KONSUMEN");
        tombolKonsumen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolKonsumenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolKonsumenMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombolKonsumenMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tombolKonsumenMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout dashPanelLayout = new javax.swing.GroupLayout(dashPanel);
        dashPanel.setLayout(dashPanelLayout);
        dashPanelLayout.setHorizontalGroup(
            dashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashPanelLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(tombolKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dashPanelLayout.setVerticalGroup(
            dashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tombolKonsumen, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        jPanel5.add(dashPanel);

        productPanel.setBackground(new java.awt.Color(0, 128, 145));
        productPanel.setPreferredSize(new java.awt.Dimension(300, 40));

        tombolPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tombolPenjualan.setForeground(new java.awt.Color(255, 255, 255));
        tombolPenjualan.setText("DATA PENJUALAN TEMPE");
        tombolPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolPenjualanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolPenjualanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombolPenjualanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tombolPenjualanMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout productPanelLayout = new javax.swing.GroupLayout(productPanel);
        productPanel.setLayout(productPanelLayout);
        productPanelLayout.setHorizontalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(tombolPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addContainerGap())
        );
        productPanelLayout.setVerticalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tombolPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(productPanel);

        customersPanel.setBackground(new java.awt.Color(0, 128, 145));
        customersPanel.setPreferredSize(new java.awt.Dimension(300, 40));

        tombolSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tombolSupplier.setForeground(new java.awt.Color(255, 255, 255));
        tombolSupplier.setText("DATA SUPPLIER");
        tombolSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolSupplierMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombolSupplierMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tombolSupplierMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout customersPanelLayout = new javax.swing.GroupLayout(customersPanel);
        customersPanel.setLayout(customersPanelLayout);
        customersPanelLayout.setHorizontalGroup(
            customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customersPanelLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(tombolSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        customersPanelLayout.setVerticalGroup(
            customersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tombolSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        jPanel5.add(customersPanel);

        salePanel.setBackground(new java.awt.Color(0, 128, 145));
        salePanel.setPreferredSize(new java.awt.Dimension(300, 40));

        tombolPembelian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tombolPembelian.setForeground(new java.awt.Color(255, 255, 255));
        tombolPembelian.setText("DATA PEMBELIAN KEDELAI");
        tombolPembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolPembelianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolPembelianMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombolPembelianMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tombolPembelianMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout salePanelLayout = new javax.swing.GroupLayout(salePanel);
        salePanel.setLayout(salePanelLayout);
        salePanelLayout.setHorizontalGroup(
            salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salePanelLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(tombolPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        salePanelLayout.setVerticalGroup(
            salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tombolPembelian, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        jPanel5.add(salePanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(67, 104, 145));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DASHBOARD ADMIN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setLayout(new java.awt.CardLayout());

        dashboardPanel.setBackground(new java.awt.Color(255, 255, 255));

        greeting.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        greeting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greeting.setText("SELAMAT DATANG ADMIN");

        waktu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(greeting, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waktu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(greeting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jPanel3.add(dashboardPanel, "card6");

        panelSupplier.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("TOTAL SUPPLIER :");

        jmlSupplier.setText("30 SUPPLIER");

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NO", "NAMA", "ALAMAT", "NO TELEPON"
            }
        ));
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSupplier);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DATA SUPPLIER");

        resfreshData.setBackground(new java.awt.Color(204, 204, 0));
        resfreshData.setText("REFRESH");
        resfreshData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resfreshDataMouseClicked(evt);
            }
        });
        resfreshData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resfreshDataActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(153, 0, 0));
        jButton10.setText("HAPUS");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        labelsupplier.setText("jLabel4");

        javax.swing.GroupLayout panelSupplierLayout = new javax.swing.GroupLayout(panelSupplier);
        panelSupplier.setLayout(panelSupplierLayout);
        panelSupplierLayout.setHorizontalGroup(
            panelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSupplierLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jmlSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(resfreshData))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSupplierLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelsupplier)
                .addGap(210, 210, 210))
        );
        panelSupplierLayout.setVerticalGroup(
            panelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSupplierLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelSupplierLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(panelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jmlSupplier))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSupplierLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelsupplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resfreshData)
                            .addComponent(jButton10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jPanel3.add(panelSupplier, "card5");

        panelPembelian.setBackground(new java.awt.Color(255, 255, 255));

        hasilJumlah.setText("80 KG");

        tblPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NO", "TANGGAL PEMBELIAN", "HARGA KEDELAI", "JUMLAH KEDELAI"
            }
        ));
        tblPembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPembelianMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPembelian);

        jLabel9.setText("TOTAL PEMBELIAN KEDELAI : ");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("DATA PEMBELIAN KEDELAI");

        hslHarga.setText("Rp 2,500,000");

        jLabel12.setText("TOTAL PENGELUARAN : ");

        jButton6.setBackground(new java.awt.Color(0, 153, 51));
        jButton6.setText("TAMBAH DATA");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 204, 0));
        jButton7.setText("REFRESH");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        labelBeli.setText("jLabel4");

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setText("HAPUS");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPembelianLayout = new javax.swing.GroupLayout(panelPembelian);
        panelPembelian.setLayout(panelPembelianLayout);
        panelPembelianLayout.setHorizontalGroup(
            panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPembelianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPembelianLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hasilJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPembelianLayout.createSequentialGroup()
                        .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelPembelianLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hslHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE))
                        .addGap(22, 22, 22))))
            .addGroup(panelPembelianLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelBeli)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelPembelianLayout.setVerticalGroup(
            panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPembelianLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelBeli)
                .addGap(30, 30, 30)
                .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(hasilJumlah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(hslHarga)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton3))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jPanel3.add(panelPembelian, "card4");

        panelKonsumen.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATA KONSUMEN");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("TOTAL KONSUMEN :");

        jButton2.setBackground(new java.awt.Color(204, 204, 0));
        jButton2.setText("REFRESH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(153, 0, 0));
        jButton9.setText("HAPUS");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        labelKonsumen.setText("jLabel4");

        javax.swing.GroupLayout panelKonsumenLayout = new javax.swing.GroupLayout(panelKonsumen);
        panelKonsumen.setLayout(panelKonsumenLayout);
        panelKonsumenLayout.setHorizontalGroup(
            panelKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelKonsumenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKonsumenLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hsl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKonsumenLayout.createSequentialGroup()
                        .addGroup(panelKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelKonsumenLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton9)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE))
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKonsumenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelKonsumen)
                .addGap(250, 250, 250))
        );
        panelKonsumenLayout.setVerticalGroup(
            panelKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKonsumenLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(labelKonsumen)
                .addGap(8, 8, 8)
                .addGroup(panelKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hsl))
                .addGap(1, 1, 1)
                .addGroup(panelKonsumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jPanel3.add(panelKonsumen, "card3");

        panelPenjualan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("TOTAL PEMASUKAN");

        jLabel14.setText("TOTAL PEMBELIAN TEMPE : ");

        hslJml.setText("80 Pcs");

        hslByr.setText("Rp 2,500,000");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("DATA PENJUALAN TEMPE");

        tblPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NO", "TANGGAL PENJUALAN", "HARGA", "JUMLAH", "TOTAL PEMBAYARAN"
            }
        ));
        tblPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPenjualanMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblPenjualan);

        btnCetak.setText("CETAK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        labelID.setText("jLabel4");

        jButton4.setBackground(new java.awt.Color(0, 153, 51));
        jButton4.setText("TAMBAH DATA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 0));
        jButton5.setText("REFRESH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(153, 0, 0));
        jButton8.setText("HAPUS");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelPenjualanLayout = new javax.swing.GroupLayout(panelPenjualan);
        panelPenjualan.setLayout(panelPenjualanLayout);
        panelPenjualanLayout.setHorizontalGroup(
            panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPenjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPenjualanLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hslJml, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 441, Short.MAX_VALUE))
                    .addGroup(panelPenjualanLayout.createSequentialGroup()
                        .addComponent(labelID)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPenjualanLayout.createSequentialGroup()
                        .addGroup(panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelPenjualanLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hslByr, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton8)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPenjualanLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
        );
        panelPenjualanLayout.setVerticalGroup(
            panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPenjualanLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(labelID)
                .addGap(18, 18, 18)
                .addGroup(panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(hslJml))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(hslByr)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton8))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCetak)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel3.add(panelPenjualan, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolPembelianMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolPembelianMouseReleased
        // TODO add your handling code here:
        salePanel.setBackground(new Color(246,89,102));
    }//GEN-LAST:event_tombolPembelianMouseReleased

    private void tombolPembelianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolPembelianMousePressed
        // TODO add your handling code here:
        salePanel.setBackground(new Color(43,44,67));
         panelPenjualan.setVisible(false);
        panelPembelian.setVisible(true);
        panelSupplier.setVisible(false);
        panelKonsumen.setVisible(false);
        dashboardPanel.setVisible(false);
        viewDataPembelian();

    }//GEN-LAST:event_tombolPembelianMousePressed

    private void tombolPembelianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolPembelianMouseExited
        // TODO add your handling code here:
        salePanel.setBackground(new Color(0,128,145));
    }//GEN-LAST:event_tombolPembelianMouseExited

    private void tombolPembelianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolPembelianMouseEntered
        // TODO add your handling code here:
        salePanel.setBackground(new Color(246,89,102));
    }//GEN-LAST:event_tombolPembelianMouseEntered

    private void tombolSupplierMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolSupplierMouseReleased
        // TODO add your handling code here:
        customersPanel.setBackground(new Color(246,89,102));
    }//GEN-LAST:event_tombolSupplierMouseReleased

    private void tombolSupplierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolSupplierMousePressed
        // TODO add your handling code here:
        customersPanel.setBackground(new Color(43,44,67));
         panelPenjualan.setVisible(false);
        panelPembelian.setVisible(false);
        panelSupplier.setVisible(true);
        panelKonsumen.setVisible(false);
        dashboardPanel.setVisible(false);
        viewDataSupplier();
    }//GEN-LAST:event_tombolSupplierMousePressed

    private void tombolSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolSupplierMouseExited
        // TODO add your handling code here:
        customersPanel.setBackground(new Color(0,128,145));
    }//GEN-LAST:event_tombolSupplierMouseExited

    private void tombolSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolSupplierMouseEntered
        // TODO add your handling code here:
        customersPanel.setBackground(new Color(246,89,102));
    }//GEN-LAST:event_tombolSupplierMouseEntered

    private void tombolPenjualanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolPenjualanMouseReleased
        // TODO add your handling code here:
        productPanel.setBackground(new Color(246,89,102));
    }//GEN-LAST:event_tombolPenjualanMouseReleased

    private void tombolPenjualanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolPenjualanMousePressed
        // TODO add your handling code here:
        productPanel.setBackground(new Color(43,44,67));
         panelPenjualan.setVisible(true);
        panelPembelian.setVisible(false);
        panelSupplier.setVisible(false);
        panelKonsumen.setVisible(false);
        dashboardPanel.setVisible(false);
        viewDataPenjualan();
    }//GEN-LAST:event_tombolPenjualanMousePressed

    private void tombolPenjualanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolPenjualanMouseExited
        // TODO add your handling code here:
        productPanel.setBackground(new Color(0,128,145));
    }//GEN-LAST:event_tombolPenjualanMouseExited

    private void tombolPenjualanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolPenjualanMouseEntered
        // TODO add your handling code here:
        productPanel.setBackground(new Color(246,89,102));
    }//GEN-LAST:event_tombolPenjualanMouseEntered

    private void tombolKonsumenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolKonsumenMouseReleased
        // TODO add your handling code here:
        dashPanel.setBackground(new Color(246,89,102));
    }//GEN-LAST:event_tombolKonsumenMouseReleased

    private void tombolKonsumenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolKonsumenMousePressed
        // TODO add your handling code here:
        dashPanel.setBackground(new Color(43,44,67));
        panelPenjualan.setVisible(false);
        panelPembelian.setVisible(false);
        panelSupplier.setVisible(false);
        panelKonsumen.setVisible(true);
        dashboardPanel.setVisible(false);
        tombolKonsumen.setBackground(new Color(246,89,102));
        viewDataKonsumen();
    }//GEN-LAST:event_tombolKonsumenMousePressed

    private void tombolKonsumenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolKonsumenMouseExited
        // TODO add your handling code here:
        dashPanel.setBackground(new Color(0,128,145));
    }//GEN-LAST:event_tombolKonsumenMouseExited

    private void tombolKonsumenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolKonsumenMouseEntered
        // TODO add your handling code here:
        dashPanel.setBackground(new Color(246,89,102));
    }//GEN-LAST:event_tombolKonsumenMouseEntered

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        String user = "root";
        String pwd = "";
        String url = "jdbc:mysql://localhost:3306/penjualantempe";
        HashMap param = new HashMap();
        JasperReport JasRep;
        JasperPrint JasPri;
        JasperDesign JasDes;
        
        try{
            Connection conn = DriverManager.getConnection(url,user,pwd);
            String path="src/Report/report1.jasper"; 
            param.put("id", labelID.getText());
            JasperPrint cetak = JasperFillManager.fillReport(path,param,conn);
            JasperViewer viewer = new JasperViewer(cetak,false);
            JasperViewer.viewReport(cetak,false);
            viewer.setFitPageZoomRatio();
            viewer.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnCetakActionPerformed

    private void tblPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPenjualanMouseClicked
        // TODO add your handling code here:
        int baris = tblPenjualan.getSelectedRow();
        String kolom1 = tblPenjualan.getValueAt(baris, 0).toString();
        
        labelID.setText(kolom1);
    }//GEN-LAST:event_tblPenjualanMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        viewDataKonsumen();
        JOptionPane.showMessageDialog(null, "Data Update !!");  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void resfreshDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resfreshDataActionPerformed
        // TODO add your handling code here:
        viewDataSupplier();
        JOptionPane.showMessageDialog(null, "Data Update !!");
    }//GEN-LAST:event_resfreshDataActionPerformed

    private void resfreshDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resfreshDataMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_resfreshDataMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        tambahPenjualan penjualan = new tambahPenjualan();
        penjualan.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        tambahPembelian beli = new tambahPembelian();
        beli.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        viewDataPembelian();
        JOptionPane.showMessageDialog(null, "Data Update !!");  

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        viewDataPenjualan();
        JOptionPane.showMessageDialog(null, "Data Update !!");  
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tblPembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPembelianMouseClicked
        // TODO add your handling code here:
        int baris = tblPembelian.getSelectedRow();
        String kolom1 = tblPembelian.getValueAt(baris, 0).toString();
        
        labelBeli.setText(kolom1);
    }//GEN-LAST:event_tblPembelianMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        int optionType = JOptionPane.OK_CANCEL_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Apakah Anda Mau menghapus Data ini", "Konfirmasi Penjualan", optionType);
        if (result == JOptionPane.OK_OPTION) {
            db.dbConnection();
            try{
                String sqlHapusPembelian="DELETE FROM pembelian_kedelai WHERE id_pembeliankedelai = "+labelBeli.getText();
                st = db.getConnection().createStatement();
                st.executeUpdate(sqlHapusPembelian);
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus, Silahkan Refresh Data !!");
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        int optionType = JOptionPane.OK_CANCEL_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Apakah Anda Mau menghapus Data ini", "Konfirmasi Penjualan", optionType);
        if (result == JOptionPane.OK_OPTION) {
            db.dbConnection();
            try{
                String sqlHapusPembelian="DELETE FROM penjualan_tempe WHERE id_penjualantempe = "+labelID.getText();
                st = db.getConnection().createStatement();
                st.executeUpdate(sqlHapusPembelian);
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus, Silahkan Refresh Data !!");
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();
        String kolom1 = jTable1.getValueAt(baris, 0).toString();
        
        labelKonsumen.setText(kolom1);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        int optionType = JOptionPane.OK_CANCEL_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Apakah Anda Mau menghapus Data ini", "Konfirmasi Penjualan", optionType);
        if (result == JOptionPane.OK_OPTION) {
            db.dbConnection();
            try{
                String sqlHapusPembelian="DELETE FROM konsumen WHERE id_konsumen = "+labelKonsumen.getText();
                st = db.getConnection().createStatement();
                st.executeUpdate(sqlHapusPembelian);
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus, Silahkan Refresh Data !!");
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
        // TODO add your handling code here:
        int baris = tblSupplier.getSelectedRow();
        String kolom1 = tblSupplier.getValueAt(baris, 0).toString();
        
        labelsupplier.setText(kolom1);
    }//GEN-LAST:event_tblSupplierMouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        int optionType = JOptionPane.OK_CANCEL_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Apakah Anda Mau menghapus Data ini", "Konfirmasi Penjualan", optionType);
        if (result == JOptionPane.OK_OPTION) {
            db.dbConnection();
            try{
                String sqlHapusPembelian="DELETE FROM supplier WHERE id_supp = "+labelsupplier.getText();
                st = db.getConnection().createStatement();
                st.executeUpdate(sqlHapusPembelian);
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus, Silahkan Refresh Data !!");
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_jButton10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }
    
 
      public void viewDataPenjualan(){
          db.dbConnection();
        DefaultTableModel model = new DefaultTableModel ();
             tblPenjualan.setModel(model);
             model.addColumn("ID");
             model.addColumn("TANGGAL PEMBELIAN");
             model.addColumn("HARGA TEMPE");
             model.addColumn("JUMLAH TEMPE");
             model.addColumn("TOTAL PEMBAYARAN");
     try{
           //membuat statemen pemanggilan data pada table tblGaji dari database
           Statement stat =  db.getConnection().createStatement();
           String sql        = "Select * from penjualan_tempe";
           ResultSet res   = stat.executeQuery(sql);
           
           //penelusuran baris pada tabel tblGaji dari database
           while(res.next ()){
                Object[ ] obj = new Object[5];
                obj[0] = res.getString("id_penjualantempe");
                obj[1] = res.getString("tanggal_penjualan");
                obj[2] = res.getString("harga_tempe");
                obj[3] = res.getString("jumlah_tempe");
                obj[4] = res.getString("total_pembayaran");
//
                model.addRow(obj);
            }
      }catch(SQLException err){}
        DefaultTableModel dataT = (DefaultTableModel) tblPenjualan.getModel();
        int jumlah = dataT.getRowCount();
        int jumlahKedelai =0;
        int hargaKedelai =0;
        
        for (int i = 0; i < jumlah; i++) {
            int jumlahkedelai = Integer.valueOf(dataT.getValueAt(i, 3).toString());
            int hargakedelai = Integer.valueOf(dataT.getValueAt(i, 4).toString());
            jumlahKedelai += jumlahkedelai;
            hargaKedelai += hargakedelai;
        }
        
        hslJml.setText(Integer.toString((int) jumlahKedelai)+" KG");
        long angka = hargaKedelai;
        String ganti = NumberFormat.getNumberInstance(Locale.US).format(angka);
        StringTokenizer token = new StringTokenizer(ganti, ".");
        ganti = token.nextToken();
        ganti = ganti.replace(',', '.');
        hslByr.setText("Rp. " + String.format(ganti));
      }

      void viewDataKonsumen(){
          db.dbConnection();
        DefaultTableModel model = new DefaultTableModel ();
             jTable1.setModel(model);
             model.addColumn("ID");
             model.addColumn("NAMA");
             model.addColumn("ALAMAT");
             model.addColumn("NO TELEPON");
     try{
           //membuat statemen pemanggilan data pada table tblGaji dari database
           Statement stat =  db.getConnection().createStatement();
           String sql        = "Select * from konsumen";
           ResultSet res   = stat.executeQuery(sql);
           
           //penelusuran baris pada tabel tblGaji dari database
           while(res.next ()){
                Object[ ] obj = new Object[4];
                obj[0] = res.getString("id_konsumen");
                obj[1] = res.getString("nama");
                obj[2] = res.getString("alamat");
                obj[3] = res.getString("no_telepon");
//
                model.addRow(obj);
            }
      }catch(SQLException err){}
      int jml = model.getRowCount();
      hsl.setText(""+jml+" Konsumen");
      }
      
      void viewDataSupplier(){
          db.dbConnection();
        DefaultTableModel model = new DefaultTableModel ();
             tblSupplier.setModel(model);
             model.addColumn("ID");
             model.addColumn("NAMA");
             model.addColumn("ALAMAT");
             model.addColumn("NO TELEPON");
     try{
           //membuat statemen pemanggilan data pada table tblGaji dari database
           Statement stat =  db.getConnection().createStatement();
           String sql        = "Select * from supplier";
           ResultSet res   = stat.executeQuery(sql);
           
           //penelusuran baris pada tabel tblGaji dari database
           while(res.next ()){
                Object[ ] obj = new Object[4];
                obj[0] = res.getString("id_supp");
                obj[1] = res.getString("nama");
                obj[2] = res.getString("alamat");
                obj[3] = res.getString("no_telepon");
//
                model.addRow(obj);
            }
      }catch(SQLException err){}
      int jml = model.getRowCount();
      jmlSupplier.setText(""+jml+" Supplier");
      }
      public void viewDataPembelian(){
          db.dbConnection();
        DefaultTableModel model = new DefaultTableModel ();
             tblPembelian.setModel(model);
             model.addColumn("ID");
             model.addColumn("TANGGAL PEMBELIAN");
             model.addColumn("HARGA KEDELAI");
             model.addColumn("JUMLAH KEDELAI");
     try{
           //membuat statemen pemanggilan data pada table tblGaji dari database
           Statement stat =  db.getConnection().createStatement();
           String sql        = "Select * from pembelian_kedelai";
           ResultSet res   = stat.executeQuery(sql);;
           
           //penelusuran baris pada tabel tblGaji dari database
           while(res.next ()){
                Object[ ] obj = new Object[4];
                obj[0] = res.getString("id_pembeliankedelai");
                obj[1] = res.getString("tanggal_pembelian");
                obj[2] = res.getString("harga_kedelai");
                obj[3] = res.getString("jumlah_kedelai");
//
                model.addRow(obj);
            }
      }catch(SQLException err){}
        DefaultTableModel dataT = (DefaultTableModel) tblPembelian.getModel();
        int jumlah = dataT.getRowCount();
        int jumlahKedelai =0;
        int hargaKedelai =0;
        
        for (int i = 0; i < jumlah; i++) {
            int jumlahkedelai = Integer.valueOf(dataT.getValueAt(i, 3).toString());
            int hargakedelai = Integer.valueOf(dataT.getValueAt(i, 2).toString());
            jumlahKedelai += jumlahkedelai;
            hargaKedelai += hargakedelai;
        }
        
        hasilJumlah.setText(Integer.toString((int) jumlahKedelai)+" KG");
        long angka = hargaKedelai;
        String ganti = NumberFormat.getNumberInstance(Locale.US).format(angka);
        StringTokenizer token = new StringTokenizer(ganti, ".");
        ganti = token.nextToken();
        ganti = ganti.replace(',', '.');
        hslHarga.setText("Rp. " + String.format(ganti));
      }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JPanel customersPanel;
    private javax.swing.JPanel dashPanel;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JLabel greeting;
    private javax.swing.JLabel hasilJumlah;
    private javax.swing.JLabel hsl;
    private javax.swing.JLabel hslByr;
    private javax.swing.JLabel hslHarga;
    private javax.swing.JLabel hslJml;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jmlSupplier;
    private javax.swing.JLabel labelBeli;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelKonsumen;
    private javax.swing.JLabel labelsupplier;
    private javax.swing.JPanel panelKonsumen;
    private javax.swing.JPanel panelPembelian;
    private javax.swing.JPanel panelPenjualan;
    private javax.swing.JPanel panelSupplier;
    private javax.swing.JPanel productPanel;
    private javax.swing.JButton resfreshData;
    private javax.swing.JPanel salePanel;
    private javax.swing.JTable tblPembelian;
    private javax.swing.JTable tblPenjualan;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JLabel tombolKonsumen;
    private javax.swing.JLabel tombolPembelian;
    private javax.swing.JLabel tombolPenjualan;
    private javax.swing.JLabel tombolSupplier;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
